export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  LOCAL_DB_UNAVAILABLE: "LOCAL_DB_UNAVAILABLE",
  LESSON_EMPTY: "LESSON_EMPTY",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  SYMBOL_NOT_FOUND: "SYMBOL_NOT_FOUND",
  DRAFT_NOT_ACTIVE: "DRAFT_NOT_ACTIVE",
  ANSWER_MISMATCH: "ANSWER_MISMATCH",
  MISTAKE_NOT_IN_BOOK: "MISTAKE_NOT_IN_BOOK"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
