export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
  STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED",
  LESSON_EMPTY: "LESSON_EMPTY",
  MISTAKE_EMPTY: "MISTAKE_EMPTY",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  QUESTION_EXHAUSTED: "QUESTION_EXHAUSTED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
